In [87]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np

In [88]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=2024-25&SeasonType=Regular%20Season&StatCategory=PTS'

In [89]:
r = requests.get(url=test_url).json()

In [90]:
table_headers = r['resultSet']['headers']

In [91]:
pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,203076,1,Anthony Davis,1610612747,LAL,3,37.7,10.7,18.7,0.571,0.7,1.7,0.400,12.0,15.0,0.800,2.3,8.7,11.0,3.3,1.7,2.3,1.3,34.0,40.0
1,1629029,1,Luka Dončić,1610612742,DAL,2,38.0,10.5,25.0,0.420,4.5,12.0,0.375,8.5,10.0,0.850,1.0,9.0,10.0,6.0,0.5,1.0,3.0,34.0,32.5
2,1629027,1,Trae Young,1610612737,ATL,2,39.0,9.0,20.0,0.450,3.5,10.0,0.350,12.5,14.5,0.862,2.0,4.5,6.5,11.0,2.5,0.5,5.0,34.0,36.5
3,1628369,4,Jayson Tatum,1610612738,BOS,3,32.3,11.7,21.3,0.547,5.7,11.7,0.486,4.0,6.0,0.667,1.0,5.3,6.3,6.0,1.3,0.7,1.0,33.0,34.7
4,1630163,5,LaMelo Ball,1610612766,CHA,3,34.3,9.7,20.7,0.468,5.0,12.0,0.417,7.3,8.0,0.917,1.3,5.7,7.0,7.3,1.0,0.7,5.7,31.7,30.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,1630696,299,Dru Smith,1610612748,MIA,2,4.5,0.0,0.5,0.000,0.0,0.0,0.000,0.0,0.0,0.000,1.0,0.0,1.0,1.0,0.0,0.5,0.5,0.0,1.5
303,1631210,299,Jacob Toppin,1610612752,NYK,2,2.5,0.0,0.5,0.000,0.0,0.5,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.5
304,204060,299,Joe Ingles,1610612750,MIN,3,5.7,0.0,0.3,0.000,0.0,0.3,0.000,0.0,0.0,0.000,0.3,0.0,0.3,2.0,0.0,0.0,0.0,0.0,2.0
305,1630699,299,MarJon Beauchamp,1610612749,MIL,2,1.0,0.0,0.5,0.000,0.0,0.5,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,-1.0
306,1641765,299,Olivier-Maxence Prosper,1610612742,DAL,2,1.5,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
del temp_df1, temp_df2, temp_df3

NameError: name 'temp_df1' is not defined

In [ ]:
df_cols = ['Year', 'Season_type'] + table_headers

In [ ]:
pd.DataFrame(columns=df_cols)

In [ ]:
headers = {
    'accept' : '*/*',
    'accept-encoding': 'gzip, deflate, br, zstd',
    'accept-language': 'en-US,en;q=0.9',
    'connection': 'keep-alive',
    'host': 'stats.nba.com',
    'origin': 'https://www.nba.com',
    'referer': 'https://www.nba.com/',
    'sec-ch-ua':'"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
}

In [ ]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                                'Season_type':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
        df = pd.concat([df, temp_df3], axis=0)
        print(f'finished scraping dating for the {y} {s}.')
        lag = np.random.uniform(low=5, high=40)
        print(f'...Waiting {round(lag,1)}')
    
        time.sleep(lag)
print(f'process completed: {round((time.time()-begin_loop)/60,2)}')    
df.to_excel('nba_player_data.xlsx', index=False)